export const CONNECT_ADD_GUIDE = 'CONNECT_ADD_GUIDE'
export const CONNECT_REMOVE_GUIDE = 'CONNECT_REMOVE_GUIDE'
export const CONNECT_SAVE_SHIPPING_ADDRESS = 'CONNECT_SAVE_SHIPPING_ADDRESS'
export const CONNECT_SAVE_PAYMENT_METHOD = 'CONNECT_SAVE_PAYMENT_METHOD'